from compiler.ast_nodes import *

class PythonGenerator:
    def __init__(self):
        self.indent_level = 0
        self.code = ""

    def emit(self, line):
        indent = "    " * self.indent_level
        self.code += f"{indent}{line}\n"

    def generate(self, node):
        self.code = "# Auto-generated by Smart Hinglish Compiler\n"
        if isinstance(node, list):
            for n in node:
                self.visit(n)
        else:
            self.visit(node)
        return self.code

    def visit(self, node):
        if node is None:
            return ""
            
        if isinstance(node, Number):
            return str(node.value)
            
        elif isinstance(node, StringLiteral):
            return f'"{node.value}"'
            
        elif isinstance(node, Identifier):
            return node.name
            
        elif isinstance(node, BinOp):
            left = self.visit(node.left)
            right = self.visit(node.right)
            return f"({left} {node.op} {right})"
            
        elif isinstance(node, Assign):
            val = self.visit(node.value)
            self.emit(f"{node.target.name} = {val}")
            
        elif isinstance(node, Print):
            val = self.visit(node.expression)
            self.emit(f"print({val})")
            
        elif isinstance(node, IfElse):
            cond = self.visit(node.condition)
            self.emit(f"if {cond}:")
            self.indent_level += 1
            for n in node.true_block:
                self.visit(n)
            self.indent_level -= 1
            
            if node.false_block:
                self.emit("else:")
                self.indent_level += 1
                for n in node.false_block:
                    self.visit(n)
                self.indent_level -= 1
                
        elif isinstance(node, WhileLoop):
            cond = self.visit(node.condition)
            self.emit(f"while {cond}:")
            self.indent_level += 1
            for n in node.body:
                self.visit(n)
            self.indent_level -= 1
            
        elif isinstance(node, ImportModule):
            self.emit(f"import {node.module_name}")

        elif isinstance(node, Poocho):
            # Hum input ko default float mein convert kar rahe hain taaki math operations ho sakein
            return "float(input())"
        
        elif isinstance(node, ArrayLiteral):
            elements_code = ", ".join([self.visit(e) for e in node.elements])
            return f"[{elements_code}]"
            
        elif isinstance(node, ArrayIndex):
            index_code = self.visit(node.index)
            return f"{node.name}[{index_code}]"
            
        elif isinstance(node, ArrayAssign):
            index_code = self.visit(node.index)
            val_code = self.visit(node.value)
            return f"{node.name}[{index_code}] = {val_code}"